//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int ID { get; set; }
        public string AuthorName { get; set; }
        public string FB_ID { get; set; }
        public string TW_ID { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string ShortBio { get; set; }
        public Nullable<bool> Status { get; set; }
        public string AuthorImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}
